//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasificationProjects.Opi.Back.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClasificationProjects.Opi.Back.Api.Resources.ApiMessages", typeof(ApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud contiene datos inválidos o incompletos..
        /// </summary>
        public static string Error_BadRequest {
            get {
                return ResourceManager.GetString("Error.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo completar la operación debido a un conflicto con el estado actual..
        /// </summary>
        public static string Error_Conflict {
            get {
                return ResourceManager.GetString("Error.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan campos requeridos o algunos valores no son válidos..
        /// </summary>
        public static string Error_FieldsInvalidOrMissing {
            get {
                return ResourceManager.GetString("Error.FieldsInvalidOrMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor no es válido..
        /// </summary>
        public static string Error_Invalid {
            get {
                return ResourceManager.GetString("Error.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El recurso solicitado no existe o no está disponible..
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado..
        /// </summary>
        public static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error.Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un registro con los mismos datos..
        /// </summary>
        public static string Error_UniqueViolation {
            get {
                return ResourceManager.GetString("Error.UniqueViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud inválida.
        /// </summary>
        public static string Title_BadRequest {
            get {
                return ResourceManager.GetString("Title.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicto.
        /// </summary>
        public static string Title_Conflict {
            get {
                return ResourceManager.GetString("Title.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encontrado.
        /// </summary>
        public static string Title_NotFound {
            get {
                return ResourceManager.GetString("Title.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inesperado.
        /// </summary>
        public static string Title_Unexpected {
            get {
                return ResourceManager.GetString("Title.Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validación fallida.
        /// </summary>
        public static string Title_Validation {
            get {
                return ResourceManager.GetString("Title.Validation", resourceCulture);
            }
        }
    }
}
